In [1]:
from sklearn.datasets import load_iris

## 1. 붓꽃 데이터 Load

In [2]:
iris_datasets = load_iris()
iris_datasets.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
#데이터(문제)
print(iris_datasets['data'].shape)
print(iris_datasets['data'][:20])
print(iris_datasets['feature_names'])

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
#레이블(답)
print(iris_datasets['target'].shape)
print(iris_datasets['target'])
print(iris_datasets['target_names'])

(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


## 2. train data 와 test data 로 나누기
train data는 머신러닝 모델을 만들때 사용하며, test data는 모델이 얼마나 잘 동작하는지
측정할때 사용되는 데이터이다.
데이터 대문자 X 로 표시하고, 레이블(답)은 소문자 y 로 표기함
f(x)=y 입력을 x , 출력을 y 
훈련데이터 X_train, 훈련데이터의레이블 y_train
테스트데이터 X_test, 테스트데이터의레이블 y_test

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = \
train_test_split(iris_datasets['data'],iris_datasets['target'],random_state=37)

In [6]:
#훈련데이터와 레이블
print(X_train.shape)
print(y_train.shape)

(112, 4)
(112,)


In [7]:
#테스트데이터와 레이블
print(X_test.shape)
print(y_test.shape)

(38, 4)
(38,)


## 3. 학습하기
KNN(K Neighbors Nearnest) 알고리즘 사용

In [8]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [9]:
#학습시키기
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [10]:
#예측하기
y_predict = model.predict(X_test)
y_predict

array([1, 0, 2, 2, 0, 1, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 2, 2, 2, 1, 0,
       2, 2, 0, 1, 2, 1, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1])

In [11]:
#평가하기
import numpy as np
np.mean(y_predict == y_test)
print('예측 정확도 점수 {:.2f}'.format(np.mean(y_predict == y_test)))

예측 정확도 점수 0.97


In [12]:
#평가하기
print('예측 정확도 점수 {:.2f}'.format(model.score(X_test,y_test)))

예측 정확도 점수 0.97
